[package]
name = "actix-web-todo-app"
version = "0.5.0"
authors = ["SL-Lee <45960387+SL-Lee@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0"
actix-identity = "0.4.0"
actix-web = "4.0.1"
argon2 = "0.4.0"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.8", features = ["chrono", "postgres", "r2d2", "uuidv07"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
rand = "0.8.5"
rand_core = "0.6.3"
serde = "1.0.137"
serde_json = "1.0.81"
tera = "1.15.0"
uuid = { version = "0.8.2", features = ["serde"] }
validator = { version = "0.15.0", features = ["derive"] }
