[package]
name = "actix-web-todo-app"
version = "0.1.0"
authors = ["SL-Lee <45960387+SL-Lee@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5.0"
actix-identity = "0.3.1"
actix-web = "3.3.2"
chrono = "0.4.19"
diesel = { version = "1.4.5", features = ["chrono", "r2d2", "sqlite"] }
dotenv = "0.15.0"
libsqlite3-sys = { version = "0.9.1", features = ["bundled"] }
json = "0.12.4"
rand = "0.8.3"
rand_core = "0.6.2"
scrypt = "0.6.3"
serde = "1.0.123"
serde_json = "1.0.64"
tera = "1.6.1"
