[package]
name = "actix-web-todo-app"
version = "0.6.0"
authors = ["SL-Lee <45960387+SL-Lee@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-identity = "0.5.2"
actix-session = { version = "0.7.1", features = ["cookie-session"] }
actix-web = "4.1.0"
argon2 = "0.4.1"
chrono = { version = "0.4.20", features = ["serde"] }
diesel = { version = "1.4.8", features = ["chrono", "postgres", "r2d2", "uuidv07"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
rand_core = "0.6.3"
serde = "1.0.142"
serde_json = "1.0.83"
tera = "1.16.0"
uuid = { version = "0.8.2", features = ["serde"] }
validator = { version = "0.16.0", features = ["derive"] }
